#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=12gb
#SBATCH --partition=hpg-turin
#SBATCH --gpus=1
#SBATCH --time=48:00:00
#SBATCH --output=%x.%j.out
#SBATCH --account=ruogu.fang
#SBATCH --qos=ruogu.fang

NUM_K=0
MODEL_DIR="/orange/ruogu.fang/tienyuchang/RETfound_results"
#microsoft/resnet-50, timm_efficientnet-b4, google/vit-base-patch16-224-in21k, RETFound_mae_natureOCT
#DATASETS=(AMD_all_split DR_binary_all_split DME_binary_all_split)  # List of datasets
#CLASSES=(2 2 2)  # Number of classes for each dataset
#DATASETS=(DME_binary_all_split)  # List of datasets
#CLASSES=(2)  # Number of classes for each dataset
STEP_PIXELS=1024
Thickness_DIR="/orange/ruogu.fang/tienyuchang/IRB2024_OCT_thickness/Data/"

MASTER_PORT=$(expr 10000 + $(echo -n $SLURM_JOBID | tail -c 4))

#python /blue/ruogu.fang/tienyuchang/RETFound_MAE/main_XAI_evaluation.py --batch_size 8 --model SMP --nb_classes 2 --data_path /orange/ruogu.fang/tienyuchang/OCTRFF_Data/data/UF-cohort/IRB2024_v5_all/split/tune8-eval2/ERM_all_split.csv --task ERM_all_split-v5-all-/blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth-XAIgradcamv2-EVAL/ --img_dir /orange/ruogu.fang/tienyuchang/IRB2024_imgs_paired/ --finetune /blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth --num_workers 8 --input_size 512 --num_k 0 --resume /orange/ruogu.fang/tienyuchang/RETfound_results/ERM_all_split-IRB2024_v5_all-all-/blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth-OCT-bs16ep100lr5e-4optadamw-defaulteval-trsub0-fuse-smpweighted_sum-pre-9-fea-2-1-0.5-decoder_to_encoder-conv---seg_mask---smp_learnable_alpha-/checkpoint-best.pth --xai gradcamv2 --step_pixels 1024 --SMPMode fuse --output_mask --thickness_dir /orange/ruogu.fang/tienyuchang/IRB2024_OCT_thickness/Data/ --target_module head --select_index -1 --smp_fuse_mode weighted_sum --smp_alpha 0.5 --smp_size_match decoder_to_encoder --fusion_dim 9 --align pre --enc_idx -2 --dec_idx -1 --smp_classifier conv --seg_mask --smp_learnable_alpha --skip_model_dependent_metrics

#python /blue/ruogu.fang/tienyuchang/RETFound_MAE/main_XAI_evaluation.py --batch_size 8 --model SMP --nb_classes 2 --data_path /orange/ruogu.fang/tienyuchang/OCTRFF_Data/data/UF-cohort/IRB2024_v5_all/split/tune8-eval2/AMD_all_split.csv --task AMD_all_split-v5-all-/blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth-XAIgradcamv2-EVAL/ --img_dir /orange/ruogu.fang/tienyuchang/IRB2024_imgs_paired/ --finetune /blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth --num_workers 8 --input_size 512 --num_k 0 --resume /orange/ruogu.fang/tienyuchang/RETfound_results/AMD_all_split-IRB2024_v5_all-all-/blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth-OCT-bs16ep100lr5e-4optadamw-defaulteval-trsub0-fuse-smpweighted_sum-pre-9-fea-2-1-0.5-decoder_to_encoder-conv---seg_mask---smp_learnable_alpha-/checkpoint-best.pth --xai gradcamv2 --step_pixels 1024 --SMPMode fuse --output_mask --thickness_dir /orange/ruogu.fang/tienyuchang/IRB2024_OCT_thickness/Data/ --target_module head --select_index -1 --smp_fuse_mode weighted_sum --smp_alpha 0.5 --smp_size_match decoder_to_encoder --fusion_dim 9 --align pre --enc_idx -2 --dec_idx -1 --smp_classifier conv --seg_mask --smp_learnable_alpha --skip_model_dependent_metrics

#python /blue/ruogu.fang/tienyuchang/RETFound_MAE/main_XAI_evaluation.py --batch_size 8 --model SMP --nb_classes 2 --data_path /orange/ruogu.fang/tienyuchang/OCTRFF_Data/data/UF-cohort/IRB2024_v5_all/split/tune8-eval2/DME_binary_all_split.csv --task DME_binary_all_split-v5-all-/blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth-XAIgradcamv2-EVAL/ --img_dir /orange/ruogu.fang/tienyuchang/IRB2024_imgs_paired/ --finetune /blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth --num_workers 8 --input_size 512 --num_k 0 --resume /orange/ruogu.fang/tienyuchang/RETfound_results/DME_binary_all_split-IRB2024_v5_all-all-/blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth-OCT-bs16ep100lr5e-4optadamw-defaulteval-trsub0-fuse-smpweighted_sum-pre-9-fea-2-1-0.5-decoder_to_encoder-conv---seg_mask---smp_learnable_alpha-/checkpoint-best.pth --xai gradcamv2 --step_pixels 1024 --SMPMode fuse --output_mask --thickness_dir /orange/ruogu.fang/tienyuchang/IRB2024_OCT_thickness/Data/ --target_module head --select_index -1 --smp_fuse_mode weighted_sum --smp_alpha 0.5 --smp_size_match decoder_to_encoder --fusion_dim 9 --align pre --enc_idx -2 --dec_idx -1 --smp_classifier conv --seg_mask --smp_learnable_alpha --skip_model_dependent_metrics

#python /blue/ruogu.fang/tienyuchang/RETFound_MAE/main_XAI_evaluation.py --batch_size 8 --model SMP --nb_classes 2 --data_path /orange/ruogu.fang/tienyuchang/OCTRFF_Data/data/UF-cohort/IRB2024_v5_all/split/tune8-eval2/Glaucoma_binary_all_split.csv --task Glaucoma_binary_all_split-v5-all-/blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth-XAIgradcamv2-EVAL/ --img_dir /orange/ruogu.fang/tienyuchang/IRB2024_imgs_paired/ --finetune /blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth --num_workers 8 --input_size 512 --num_k 0 --resume /orange/ruogu.fang/tienyuchang/RETfound_results/Glaucoma_binary_all_split-IRB2024_v5_all-all-/blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth-OCT-bs16ep100lr5e-4optadamw-defaulteval-trsub0-fuse-smpweighted_sum-pre-9-fea-2-1-0.5-decoder_to_encoder-conv---seg_mask---smp_learnable_alpha-/checkpoint-best.pth --xai gradcamv2 --step_pixels 1024 --SMPMode fuse --output_mask --thickness_dir /orange/ruogu.fang/tienyuchang/IRB2024_OCT_thickness/Data/ --target_module head --select_index -1 --smp_fuse_mode weighted_sum --smp_alpha 0.5 --smp_size_match decoder_to_encoder --fusion_dim 9 --align pre --enc_idx -2 --dec_idx -1 --smp_classifier conv --seg_mask --smp_learnable_alpha --skip_model_dependent_metrics

#python /blue/ruogu.fang/tienyuchang/RETFound_MAE/main_XAI_evaluation.py --batch_size 2 --model SMP --nb_classes 2 --data_path /orange/ruogu.fang/tienyuchang/OCTDL/AMD_all.csv --task AMD_all-OCTDL-all-/blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth-XAIgradcamv2-EVAL/ --img_dir /orange/ruogu.fang/tienyuchang/OCTDL/ --thickness_dir /orange/ruogu.fang/tienyuchang/OCTDL_masks_multiclass_resnet50_new/ --finetune /blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth --num_workers 8 --input_size 512 --num_k 0 --resume /orange/ruogu.fang/tienyuchang/RETfound_results/AMD_all-OCTDL-all-/blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth-OCT-bs16ep50lr1e-4optadamw-defaulteval-trsub0-fuse-smpweighted_sum-pre-9-fea-2-1-0.5-decoder_to_encoder-conv---seg_mask---smp_learnable_alpha-/checkpoint-best.pth --xai gradcamv2 --step_pixels 1024 --SMPMode fuse --output_mask --target_module head --select_index -1 --smp_fuse_mode weighted_sum --smp_alpha 0.5 --smp_size_match decoder_to_encoder --fusion_dim 9 --enc_idx -2 --dec_idx -1 --smp_classifier conv --seg_mask --smp_learnable_alpha --skip_model_dependent_metrics

#python /blue/ruogu.fang/tienyuchang/RETFound_MAE/main_XAI_evaluation.py --batch_size 2 --model SMP --nb_classes 2 --data_path /orange/ruogu.fang/tienyuchang/OCTDL/DME_all.csv --task DME_all-OCTDL-all-/blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth-XAIgradcamv2-EVAL/ --img_dir /orange/ruogu.fang/tienyuchang/OCTDL/ --thickness_dir /orange/ruogu.fang/tienyuchang/OCTDL_masks_multiclass_resnet50_new/ --finetune /blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth --num_workers 8 --input_size 512 --num_k 0 --resume /orange/ruogu.fang/tienyuchang/RETfound_results/DME_all-OCTDL-all-/blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth-OCT-bs16ep50lr1e-4optadamw-defaulteval-trsub0-fuse-smpweighted_sum-pre-9-fea-2-1-0.5-decoder_to_encoder-conv---seg_mask---smp_learnable_alpha-/checkpoint-best.pth --xai gradcamv2 --step_pixels 1024 --SMPMode fuse --output_mask --target_module head --select_index -1 --smp_fuse_mode weighted_sum --smp_alpha 0.5 --smp_size_match decoder_to_encoder --fusion_dim 9 --enc_idx -2 --dec_idx -1 --smp_classifier conv --seg_mask --smp_learnable_alpha --skip_model_dependent_metrics

#python /blue/ruogu.fang/tienyuchang/RETFound_MAE/main_XAI_evaluation.py --batch_size 2 --model SMP --nb_classes 2 --data_path /orange/ruogu.fang/tienyuchang/CellData/OCT/DME_all.csv --thickness_dir /orange/ruogu.fang/tienyuchang/CellData_masks_multiclass_resnet50_new/ --task DME_all-CellData-all-/blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass.pth-XAIgradcamv2-EVAL/ --img_dir /orange/ruogu.fang/tienyuchang/CellData/ --finetune /blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass.pth --num_workers 8 --input_size 512 --num_k 0 --resume /orange/ruogu.fang/tienyuchang/RETfound_results/DME_all-CellData-all-/blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth-OCT-bs16ep5lr1e-4optadamw-defaulteval-trsub0-fuse-smpweighted_sum-pre-9-fea-2-1-0.5-decoder_to_encoder-conv---seg_mask---smp_learnable_alpha-/checkpoint-best.pth --xai gradcamv2 --step_pixels 1024 --SMPMode fuse --output_mask --target_module head --select_index -1 --smp_fuse_mode weighted_sum --smp_alpha 0.5 --smp_size_match decoder_to_encoder --fusion_dim 9 --enc_idx -2 --dec_idx -1 --smp_classifier conv --seg_mask --smp_learnable_alpha --skip_model_dependent_metrics

#python /blue/ruogu.fang/tienyuchang/RETFound_MAE/main_XAI_evaluation.py --batch_size 8 --model SMP --nb_classes 2 --data_path /orange/ruogu.fang/tienyuchang/OCTRFF_Data/data/UF-cohort/IRB2024_v5_all/split/tune8-eval2/ERM_all_split.csv --task ERM_all_split-v5-all-/blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth-XAIcrp-EVAL/ --img_dir /orange/ruogu.fang/tienyuchang/IRB2024_imgs_paired/ --finetune /blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth --num_workers 8 --input_size 512 --num_k 0 --resume /orange/ruogu.fang/tienyuchang/RETfound_results/ERM_all_split-IRB2024_v5_all-all-/blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth-OCT-bs16ep100lr5e-4optadamw-defaulteval-trsub0-fuse-smpweighted_sum-pre-9-fea-2-1-0.5-decoder_to_encoder-conv---seg_mask---smp_learnable_alpha-/checkpoint-best.pth --xai crp --step_pixels 1024 --SMPMode fuse --output_mask --thickness_dir /orange/ruogu.fang/tienyuchang/IRB2024_OCT_thickness/Data/ --target_module head --select_index -1 --smp_fuse_mode weighted_sum --smp_alpha 0.5 --smp_size_match decoder_to_encoder --fusion_dim 9 --align pre --enc_idx -2 --dec_idx -1 --smp_classifier conv --seg_mask --smp_learnable_alpha

#python /blue/ruogu.fang/tienyuchang/RETFound_MAE/main_XAI_evaluation.py --batch_size 8 --model SMP --nb_classes 2 --data_path /orange/ruogu.fang/tienyuchang/OCTRFF_Data/data/UF-cohort/IRB2024_v5_all/split/tune8-eval2/AMD_all_split.csv --task AMD_all_split-v5-all-/blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth-XAIcrp-EVAL/ --img_dir /orange/ruogu.fang/tienyuchang/IRB2024_imgs_paired/ --finetune /blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth --num_workers 8 --input_size 512 --num_k 0 --resume /orange/ruogu.fang/tienyuchang/RETfound_results/AMD_all_split-IRB2024_v5_all-all-/blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth-OCT-bs16ep100lr5e-4optadamw-defaulteval-trsub0-fuse-smpweighted_sum-pre-9-fea-2-1-0.5-decoder_to_encoder-conv---seg_mask---smp_learnable_alpha-/checkpoint-best.pth --xai crp --step_pixels 1024 --SMPMode fuse --output_mask --thickness_dir /orange/ruogu.fang/tienyuchang/IRB2024_OCT_thickness/Data/ --target_module head --select_index -1 --smp_fuse_mode weighted_sum --smp_alpha 0.5 --smp_size_match decoder_to_encoder --fusion_dim 9 --align pre --enc_idx -2 --dec_idx -1 --smp_classifier conv --seg_mask --smp_learnable_alpha

#python /blue/ruogu.fang/tienyuchang/RETFound_MAE/main_XAI_evaluation.py --batch_size 8 --model SMP --nb_classes 2 --data_path /orange/ruogu.fang/tienyuchang/OCTRFF_Data/data/UF-cohort/IRB2024_v5_all/split/tune8-eval2/DME_binary_all_split.csv --task DME_binary_all_split-v5-all-/blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth-XAIcrp-EVAL/ --img_dir /orange/ruogu.fang/tienyuchang/IRB2024_imgs_paired/ --finetune /blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth --num_workers 8 --input_size 512 --num_k 0 --resume /orange/ruogu.fang/tienyuchang/RETfound_results/DME_binary_all_split-IRB2024_v5_all-all-/blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth-OCT-bs16ep100lr5e-4optadamw-defaulteval-trsub0-fuse-smpweighted_sum-pre-9-fea-2-1-0.5-decoder_to_encoder-conv---seg_mask---smp_learnable_alpha-/checkpoint-best.pth --xai crp --step_pixels 1024 --SMPMode fuse --output_mask --thickness_dir /orange/ruogu.fang/tienyuchang/IRB2024_OCT_thickness/Data/ --target_module head --select_index -1 --smp_fuse_mode weighted_sum --smp_alpha 0.5 --smp_size_match decoder_to_encoder --fusion_dim 9 --align pre --enc_idx -2 --dec_idx -1 --smp_classifier conv --seg_mask --smp_learnable_alpha

#python /blue/ruogu.fang/tienyuchang/RETFound_MAE/main_XAI_evaluation.py --batch_size 8 --model SMP --nb_classes 2 --data_path /orange/ruogu.fang/tienyuchang/OCTRFF_Data/data/UF-cohort/IRB2024_v5_all/split/tune8-eval2/Glaucoma_binary_all_split.csv --task Glaucoma_binary_all_split-v5-all-/blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth-XAIcrp-EVAL/ --img_dir /orange/ruogu.fang/tienyuchang/IRB2024_imgs_paired/ --finetune /blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth --num_workers 8 --input_size 512 --num_k 0 --resume /orange/ruogu.fang/tienyuchang/RETfound_results/Glaucoma_binary_all_split-IRB2024_v5_all-all-/blue/ruogu.fang/tienyuchang/RETFound_MAE/Seg_checkpoints/best_model_multiclass_resnet50_new.pth-OCT-bs16ep100lr5e-4optadamw-defaulteval-trsub0-fuse-smpweighted_sum-pre-9-fea-2-1-0.5-decoder_to_encoder-conv---seg_mask---smp_learnable_alpha-/checkpoint-best.pth --xai crp --step_pixels 1024 --SMPMode fuse --output_mask --thickness_dir /orange/ruogu.fang/tienyuchang/IRB2024_OCT_thickness/Data/ --target_module head --select_index -1 --smp_fuse_mode weighted_sum --smp_alpha 0.5 --smp_size_match decoder_to_encoder --fusion_dim 9 --align pre --enc_idx -2 --dec_idx -1 --smp_classifier conv --seg_mask --smp_learnable_alpha
