#!/bin/bash
# Enhanced Fairness Analysis with Uncertainty Quantification
# 
# This script demonstrates how to use the enhanced fairness evaluation function
# that integrates your existing fairness matrix with uncertainty quantification
# and confidence interval calculations.

echo "=============================================================="
echo "Enhanced Fairness Analysis with Uncertainty Quantification"
echo "=============================================================="

# Base configuration
MODEL_CONFIG="--model vit_large_patch16 --task fairness_analysis_example --nb_classes 2"
DATA_CONFIG="--data_path ./data/dataset.csv --batch_size 32"
EVAL_CONFIG="--eval --resume ./checkpoints/best_model.pth"
OUTPUT_CONFIG="--output_dir ./results --log_dir ./logs"

# Enhanced fairness and uncertainty parameters
FAIRNESS_UNCERTAINTY_CONFIG="--conformal_alpha 0.1 \
                            --roc_strategy accuracy_coverage \
                            --calibration_bins 10 \
                            --cal_split_ratio 0.5 \
                            --n_bootstrap 1000 \
                            --confidence_level 0.95 \
                            --outcome_flag binary \
                            --save_fairness_plots \
                            --export_detailed_results"

# Full command
BASE_CMD="python main_finetune_Chua_Jacqueline.py"
FULL_CMD="$BASE_CMD $MODEL_CONFIG $DATA_CONFIG $EVAL_CONFIG $FAIRNESS_UNCERTAINTY_CONFIG $OUTPUT_CONFIG"

echo "Command to run:"
echo "$FULL_CMD"
echo ""

echo "=============================================================="
echo "Key Features of Enhanced Fairness Analysis:"
echo "=============================================================="
echo ""
echo "🎯 UNCERTAINTY QUANTIFICATION:"
echo "  ✓ Reject Option Classification with confidence thresholds"
echo "  ✓ Conformal Prediction with 90% coverage guarantee"
echo "  ✓ Model calibration assessment (ECE, reliability diagrams)"
echo "  ✓ Group-wise uncertainty analysis for protected/privileged groups"
echo ""
echo "⚖️  FAIRNESS ANALYSIS WITH CONFIDENCE INTERVALS:"
echo "  ✓ Your existing fairness matrix (PPV, FPR, TPR, NPV, TE, FNR, ACC)"
echo "  ✓ Bootstrap confidence intervals for all fairness metrics"
echo "  ✓ Statistical significance testing for fairness differences"
echo "  ✓ Visualization with error bars and significance indicators"
echo ""
echo "📊 ENHANCED METRICS COMPUTED:"
echo "  ✓ Protected vs Privileged group differences with 95% CI"
echo "  ✓ Uncertainty metrics per demographic group"
echo "  ✓ Calibration fairness across groups"
echo "  ✓ Coverage and accuracy differences with confidence bounds"
echo ""

echo "=============================================================="
echo "Expected Output Structure:"
echo "=============================================================="
echo ""
echo "results/"
echo "├── fairness_analysis_example/"
echo "│   └── fairness_uncertainty_analysis/"
echo "│       ├── uncertainty_results.json"
echo "│       ├── fairness_ci_results.json"
echo "│       └── fairness_metrics_with_ci.png"
echo ""

echo "=============================================================="
echo "Sample Output Metrics:"
echo "=============================================================="
echo ""
echo "=== ENHANCED FAIRNESS ANALYSIS ==="
echo "Original fairness metrics: (0.85, 0.82, 0.15, 0.18, 0.88, 0.85, ...)"
echo ""
echo "--- Uncertainty Quantification ---"
echo "ROC Optimal Threshold: 0.750"
echo "ROC Coverage: 0.823"
echo "ROC Accuracy (accepted): 0.912"
echo "ROC Rejection Rate: 0.177"
echo "Conformal Target Coverage: 0.900"
echo "Conformal Empirical Coverage: 0.894"
echo "Conformal Average Set Size: 1.156"
echo "Conformal Singleton Rate: 0.867"
echo "Expected Calibration Error (ECE): 0.0234"
echo ""
echo "--- Fairness Analysis with Confidence Intervals ---"
echo "Fairness Analysis (Bootstrap samples: 987)"
echo "Confidence Level: 95.0%"
echo ""
echo "Fairness Differences (Privileged - Protected):"
echo "PPV_diff: -0.0234 [-0.0456, -0.0012] ***"
echo "FPR_diff: 0.0187 [-0.0034, 0.0408] n.s."
echo "TPR_diff: -0.0298 [-0.0567, -0.0029] ***"
echo "ACC_diff: -0.0156 [-0.0312, 0.0001] n.s."
echo ""
echo "--- Group-wise Uncertainty Analysis ---"
echo "Protected Group - ROC Coverage: 0.798, Accuracy: 0.923"
echo "Privileged Group - ROC Coverage: 0.834, Accuracy: 0.901"
echo "Protected Group Coverage CI: [0.765, 0.831]"
echo "Protected Group Accuracy CI: [0.889, 0.957]"
echo "Privileged Group Coverage CI: [0.801, 0.867]"
echo "Privileged Group Accuracy CI: [0.867, 0.935]"
echo ""

echo "=============================================================="
echo "Parameter Explanations:"
echo "=============================================================="
echo ""
echo "--conformal_alpha 0.1     : 90% coverage target for conformal prediction"
echo "--roc_strategy             : How to select optimal rejection threshold"
echo "--calibration_bins 10      : Number of bins for calibration assessment"
echo "--cal_split_ratio 0.5      : Split ratio for calibration vs evaluation"
echo "--n_bootstrap 1000         : Bootstrap samples for confidence intervals"
echo "--confidence_level 0.95    : 95% confidence intervals"
echo "--outcome_flag binary      : Binary classification fairness analysis"
echo "--save_fairness_plots      : Generate visualization plots"
echo "--export_detailed_results  : Save detailed JSON results"
echo ""

echo "=============================================================="
echo "Key Advantages of Enhanced Analysis:"
echo "=============================================================="
echo ""
echo "1. 📈 STATISTICAL RIGOR:"
echo "   - Bootstrap confidence intervals provide uncertainty bounds"
echo "   - Statistical significance testing identifies real vs random differences"
echo "   - Multiple comparison correction available"
echo ""
echo "2. 🎯 UNCERTAINTY-AWARE FAIRNESS:"
echo "   - Analyzes fairness under model uncertainty"
echo "   - Group-specific rejection rates and calibration"
echo "   - Confidence-based fairness assessment"
echo ""
echo "3. 🔍 COMPREHENSIVE REPORTING:"
echo "   - Integrates with your existing fairness matrix"
echo "   - Detailed JSON exports for further analysis"
echo "   - Publication-ready visualizations"
echo ""
echo "4. ⚡ PRODUCTION READY:"
echo "   - Robust error handling and fallback to basic metrics"
echo "   - Configurable parameters for different use cases"
echo "   - Seamless integration with existing pipeline"
echo ""

echo "=============================================================="
echo "Usage Notes:"
echo "=============================================================="
echo ""
echo "• The function automatically uses your existing fariness_score() function"
echo "• Protected/privileged groups are defined by protect_image_names/prevalent_image_names"
echo "• All uncertainty methods work with any number of classes"
echo "• Confidence intervals use bootstrap sampling (adjustable sample size)"
echo "• Statistical significance uses non-overlapping CI method"
echo "• Plots show error bars and significance indicators"
echo "• Results are saved with timestamps for experiment tracking"
echo ""
echo "Ready to run enhanced fairness analysis!"
